package com.vwapcalculator.app.disruptor;

import com.lmax.disruptor.ExceptionHandler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Handles the exception generated by event processors or any other exception during batch processing
 * from the disruptor
 */
public class DefaultExceptionHandler implements ExceptionHandler<MarketUpdateEvent> {
    private static final Logger LOGGER = LoggerFactory.getLogger(DefaultExceptionHandler.class);

    @Override
    public void handleEventException(Throwable ex, long sequence, MarketUpdateEvent event) {
        LOGGER.error("Error handling event at seq=" + sequence + " event " + event) ;
        ex.printStackTrace();
    }

    @Override
    public void handleOnStartException(Throwable ex) {
        LOGGER.error("Error during start process");
        ex.printStackTrace();
    }

    @Override
    public void handleOnShutdownException(Throwable ex) {
        LOGGER.error("Error during shutdown process");
        ex.printStackTrace();
    }
}
